# soft_delete_retention_days = 7
# purge_protection_enabled   = false
# sku_name_kv                = "standard"
rg_novo                    = false
kv_existente               = true
rg_existente               = true
rg_name                    = "rgnewrvs"
kv_name                    = "kvrvstfsda"
rg_location                = "eastus"
kv_novo                    = false
