# soft_delete_retention_days = 7
# purge_protection_enabled   = false
kv_novo                    = false
kv_existente               = true
kv_name                    = "kvrvstfsd"
sku_name_kv                = "standard"
rg_name                    = "testerg"
rg_location                = "eastus"
rg_novo                    = false
rg_existente               = true
specific_object_id  	   = "449b6f29-c827-4067-a44a-8fd8dc43445c"