name: Terraform, Azure CLI, and Annotations Workflow

on:
  push:
    branches:
      - "main"
  pull_request:

permissions:
  contents: read
  id-token: write

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    environment: development

    steps:
      # Step 1: Checkout repository
      - name: Checkout
        uses: actions/checkout@v4

      # Step 2: Setup Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      # Step 3: Terraform Initialization
      - name: Terraform Init
        env:
          AZURE_CLIENT_ID_DEV: ${{ secrets.AZURE_CLIENT_ID_DEV }}
        run: terraform init

      # Step 4: Terraform Plan
      - name: Terraform Plan
        env:
          AZURE_CLIENT_ID_DEV: ${{ secrets.AZURE_CLIENT_ID_DEV }}
        run: terraform plan -var "azure_client_id=${{ secrets.AZURE_CLIENT_ID_DEV }}" -input=false

      # Step 5: Terraform Apply
      - name: Terraform Apply
        env:
          AZURE_CLIENT_ID_DEV: ${{ secrets.AZURE_CLIENT_ID_DEV }}
        run: terraform apply -var "azure_client_id=${{ secrets.AZURE_CLIENT_ID_DEV }}" -input=false -auto-approve


  # azure-cli-prd:
  #   name: 'Azure CLI Production'
  #   runs-on: ubuntu-latest
  #   environment: production

  #   needs: terraform # Ensures Terraform job completes before running Azure CLI job

  #   defaults:
  #     run:
  #       shell: bash

  #   steps:
  #     # Step 1: Checkout repository
  #     - name: Checkout
  #       uses: actions/checkout@v4

  #     # Step 2: Login to Azure CLI
  #     - name: Azure CLI Login
  #       uses: azure/login@v2
  #       with:
  #         client-id: ${{ secrets.AZURE_CLIENT_ID_PRD }}
  #         tenant-id: ${{ secrets.AZURE_TENANT_ID }}
  #         subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID_PRD }}

  #     # Step 3: Execute Azure CLI Commands
  #     - name: Azure CLI script
  #       uses: azure/cli@v2
  #       with:
  #         azcliversion: latest
  #         inlineScript: |
  #           az account show
  #           # Add additional Azure CLI commands as needed