name: Terraform, Azure CLI, and ESLint Workflow

on:
  push:
    branches: [ "main" ]
  pull_request:

permissions:
  contents: read
  id-token: write

jobs:
  terraform:
    name: 'Terraform Job'
    runs-on: ubuntu-latest
    environment: production

    defaults:
      run:
        shell: bash

    steps:
      # Step 1: Checkout repository
      - name: Checkout
        uses: actions/checkout@v4

      # Step 2: Setup Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      # Step 3: Terraform Initialization
      - name: Terraform Init
        run: terraform init

      # Step 4: Terraform Plan
      - name: Terraform Plan
        run: terraform plan -input=false

  azure-cli:
    name: 'Azure CLI Job'
    runs-on: ubuntu-latest
    environment: production

    needs: terraform # Ensures Terraform job completes after the Terraform job

    defaults:
      run:
        shell: bash

    steps:
      # Step 1: Checkout repository
      - name: Checkout
        uses: actions/checkout@v4

      # Step 2: Login to Azure CLI
      - name: Azure CLI Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      # Step 3: Execute Azure CLI Commands
      - name: Azure CLI script
        uses: azure/cli@v2
        with:
          azcliversion: latest
          inlineScript: |
            az account show
            # Add additional Azure CLI commands as needed

  eslint:
    name: 'ESLint Job'
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    steps:
      # Step 1: Checkout repository
      - name: Checkout
        uses: actions/checkout@v4

      # Step 2: Set up Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16' # Specify the Node.js version you use

      # Step 3: Install dependencies
      - name: Install Dependencies
        run: npm install

      # Step 4: Run ESLint
      - name: Run ESLint
        run: |
          npx eslint . --format json -o eslint-report.json

      # Step 5: Create Annotations for ESLint Issues
      - name: Annotate ESLint Issues
        run: |
          jq -c '.[] | "::error file=" + .filePath + ",line=" + (.line|tostring) + "::" + .message' eslint-report.json | xargs -I{} echo {}
