name: Terraform and Azure CLI Workflow

on:
  push:
    branches: [ "main" ]
  pull_request:

permissions:
  contents: read
  id-token: write

jobs:
  terraform:
    name: 'Terraform Job'
    runs-on: ubuntu-latest
    environment: production

    defaults:
      run:
        shell: bash

    steps:
      # Step 1: Checkout repository
      - name: Checkout
        uses: actions/checkout@v4

      # Step 2: Setup Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      # Step 3: Initialize Terraform
      - name: Initialize
        run: terraform init

      # Step 4: Plan Terraform
      - name: Plan
        run: terraform plan -out .planfile

      # Step 5: Post PR Comment
      # This step only runs for pull request events
      - name: Post PR Comment
        if: github.event_name == 'pull_request'
        uses: borchero/terraform-plan-comment@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          planfile: .planfile

  azure-cli:
    name: 'Azure CLI Job'
    runs-on: ubuntu-latest
    environment: production

    needs: terraform # Ensures Terraform job completes before running Azure CLI job

    defaults:
      run:
        shell: bash

    steps:
      # Step 1: Checkout repository
      - name: Checkout
        uses: actions/checkout@v4

      # Step 2: Login to Azure CLI
      - name: Azure CLI Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      # Step 3: Execute Azure CLI Commands
      - name: Azure CLI script
        uses: azure/cli@v2
        with:
          azcliversion: latest
          inlineScript: |
            az account show
            # Add additional Azure CLI commands as needed
