name: Terraform, Azure CLI, and Annotations Workflow

on:
  push:
    branches:
      - "main"
  pull_request:

permissions:
  contents: read
  id-token: write

jobs:
  terraform-dev:
    name: 'Terraform'
    runs-on: ubuntu-latest
    environment: development

    steps:
      # Step 1: Checkout repository
      - name: Checkout
        uses: actions/checkout@v4

      # Step 2: Install Azure CLI
      - name: Install Azure CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y azure-cli

      # Step 2: Login to Azure CLI
      - name: Azure CLI Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID_DEV }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID_DEV }}

      # Step 4: Setup Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      # Step 5: Terraform Initialization
      - name: Terraform Init
        run: terraform init

      # Step 6: Terraform Plan
      - name: Terraform Plan
        run: terraform plan -var="client_id=${{secrets.AZURE_CLIENT_ID_DEV}}" -var="environment=${{ secrets.ENVIRONMENT_DEV }}"

      # Step 7: Terraform Apply
      - name: Terraform Apply
        run: terraform apply -var="client_id=${{secrets.AZURE_CLIENT_ID_DEV}}" -var="environment=${{ secrets.ENVIRONMENT_DEV }}" -auto-approve

  manual-approval:
    name: Manual Approval
    runs-on: ubuntu-latest
    needs: terraform-dev
    if: success() # Only proceed if terraform-plan job succeeds
    
    permissions:
      issues: write

    steps:
      - name: Await Manual Approval
        uses: trstringer/manual-approval@v1
        with:
          secret: ${{ github.TOKEN }}
          approvers: rafaveloso23 # Replace with GitHub usernames, with the free version you can only have an issue assigned to one username
          minimum-approvals: 1
          issue-title: "Manual Approval Required for Terraform Apply"
          issue-body: "Please approve or deny the deployment."

  # # terraform-prd:
  #   name: 'Terraform'
  #   runs-on: ubuntu-latest
  #   needs: manual-approval
  #   environment: production

  #   steps:
  #     # Step 1: Checkout repository
  #     - name: Checkout
  #       uses: actions/checkout@v4

  #     # Step 2: Install Azure CLI
  #     - name: Install Azure CLI
  #       run: |
  #         sudo apt-get update
  #         sudo apt-get install -y azure-cli

  #     # Step 2: Login to Azure CLI
  #     - name: Azure CLI Login
  #       uses: azure/login@v2
  #       with:
  #         client-id: ${{ secrets.AZURE_CLIENT_ID_PRD }}
  #         tenant-id: ${{ secrets.AZURE_TENANT_ID }}
  #         subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID_PRD }}

  #     # Step 4: Setup Terraform
  #     - name: Setup Terraform
  #       uses: hashicorp/setup-terraform@v1
  #       with:
  #         cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

  #     # Step 5: Terraform Initialization
  #     - name: Terraform Init
  #       run: terraform init

  #     # Step 6: Terraform Plan
  #     - name: Terraform Plan
  #       run: terraform plan -var="environment=${{ secrets.ENVIRONMENT_PRD }}" -auto-approve